### ISSUE TITLE
Help for first install

### ISSUE THREAD

**Issue by jayboc** [bauerdaniel/OnkyoRemote#1]
Thanks for sharing. I definitely need that. Do you have easy startup instruction after git cloning ? Best regards

**Comment by bauerdaniel** [comment]
Thanks for your interest!

I have added installation instructions to the README. There are a few minor differences if you are using Windows. The home directory for Windows would be C:\Users\<User>. The environment variable settings can be found in the system properties dialog of the control panel.

It is just important that you copy the Onkyo.exe into a folder that you can add to the PATH environment variable later. This allows you to run the app anywhere in the terminal.

Feel free to let me know if you got it working.

**Comment by jayboc** [comment]
Pretty successful first install :+1, thanks for sharing, I couldn't choose my device between my NCP and TX-NR : 

@ThinkPad-T450s:~$ onkyo discover
No valid config file found
Discovering devices...
Receive timeout is set to 5 seconds
Sending broadcast message to: 192.168.2.255:60128
Sending broadcast message to: 192.168.250.1:60128
Sending broadcast message to: 10.0.3.255:60128
Available devices:

        0: TX-NR686 at 192.168.2.44:60128
        0: NCP-302 at 192.168.2.56:60128

Selected device: 0
@ThinkPad-T450s:~$ onkyo list
Available devices:

        0: TX-NR686 at 192.168.2.44:60128
        0: NCP-302 at 192.168.2.56:60128

Selected device: 0
ThinkPad-T450s:~$ onkyo on
⚡
ThinkPad-T450s:~$ onkyo off
❌
ThinkPad-T450s:~$

**Comment by bauerdaniel** [comment]
Thanks for reporting. Should be fixed now.

**Comment by jayboc** [comment]
resolved issue
